package com.example.loldatabase;

import com.example.lolattributesearcher.R;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DBHelper extends SQLiteOpenHelper{
	/*
	 * This class is to
	 * Create DB
	 * Update DB
	 */
	private static final String DB_NAME = "lol.db";
	private static final int DB_VER = 2;
	
	public DBHelper(Context context)	{
		super(context,DB_NAME,null,DB_VER);
		
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		//Create 3 Tables
		String sql = "create table champion_db(" + "C_id integer primary key autoincrement,"
		+"name text,"
		+"path integer);";
		db.execSQL(sql);
		sql = "create table champion2attribute_db(" + "_id integer primary key autoincrement,"
		 + "C_id integer,"
				+"A_id integer);";
		db.execSQL(sql);
		sql = "create table attribute_db(" + "A_id integer primary key autoincrement,"
		+ "name text, " 
		+ "description text)";
		db.execSQL(sql);	
		
		//Insert Champion Data in Champion_db Table
		sql = "insert into champion_db (name, path) values(" + "'Aatrox', " + R.drawable.aatroxsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Ahri', " + R.drawable.ahrisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Akali', " + R.drawable.akalisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Amumu', " + R.drawable.amumusquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Anivia', " + R.drawable.aniviasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Annie', " + R.drawable.anniesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Ashe', " + R.drawable.ashesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Blitzcrank', " + R.drawable.blitzcranksquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Brand', " + R.drawable.brandsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Caitlyn', " + R.drawable.caitlynsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Cassiopeia', " + R.drawable.cassiopeiasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Cho''Gath', " + R.drawable.chogathsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Corki', " + R.drawable.corkisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Darius', " + R.drawable.dariussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Diana', " + R.drawable.dianasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Dr. Mundo', " + R.drawable.drmundosquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Draven', " + R.drawable.dravensquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Elise', " + R.drawable.elisesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Evelynn', " + R.drawable.evelynnsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Ezreal', " + R.drawable.ezrealsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Fiddlesticks', " + R.drawable.fiddlestickssquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Fiora', " + R.drawable.fiorasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Fizz', " + R.drawable.fizzsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Galio', " + R.drawable.galiosquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Gangplank', " + R.drawable.gangplanksquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Garen', " + R.drawable.garensquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Gragas', " + R.drawable.gragassquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Graves', " + R.drawable.gravessquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Hecarim', " + R.drawable.hecarimsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Heimerdinger', " + R.drawable.heimerdingersquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Irelia', " + R.drawable.ireliasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Janna', " + R.drawable.jannasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Jarvan IV', " + R.drawable.jarvanivsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Jax', " + R.drawable.jaxsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Jayce', " + R.drawable.jaycesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Jinx', " + R.drawable.jinxsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Karma', " + R.drawable.karmasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Karthus', " + R.drawable.karthussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Kassadin', " + R.drawable.kassadinsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Katarina', " + R.drawable.katarinasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Kayle', " + R.drawable.kaylesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Kennen', " + R.drawable.kennensquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Kha''Zix', " + R.drawable.khazixsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Kog''Maw', " + R.drawable.kogmawsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'LeBlanc', " + R.drawable.leblancsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Lee Sin', " + R.drawable.leesinsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Leona', " + R.drawable.leonasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Lissandra', " + R.drawable.lissandrasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Lucian', " + R.drawable.luciansquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Lulu', " + R.drawable.lulusquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Lux', " + R.drawable.luxsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Malphite', " + R.drawable.malphitesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Malzahar', " + R.drawable.malzaharsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Maokai', " + R.drawable.maokaisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Master Yi', " + R.drawable.masteryisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Miss Fortune', " + R.drawable.missfortunesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Mordekaiser', " + R.drawable.mordekaisersquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Morgana', " + R.drawable.morganasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nami', " + R.drawable.namisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nasus', " + R.drawable.nasussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nautilus', " + R.drawable.nautilussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nidalee', " + R.drawable.nidaleesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nocturne', " + R.drawable.nocturnesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Nunu', " + R.drawable.nunusquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Olaf', " + R.drawable.olaf_newsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Orianna', " + R.drawable.oriannasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Pantheon', " + R.drawable.pantheonsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Poppy', " + R.drawable.poppysquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Quinn', " + R.drawable.quinnsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Rammus', " + R.drawable.rammussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Renekton', " + R.drawable.renektonsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Rengar', " + R.drawable.rengarsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Riven', " + R.drawable.rivensquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Rumble', " + R.drawable.rumblesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Ryze', " + R.drawable.ryzesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Sejuani', " + R.drawable.sejuanisquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Shaco', " + R.drawable.shacosquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Shen', " + R.drawable.shensquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Shyvana', " + R.drawable.shyvanasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Singed', " + R.drawable.singedsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Sion', " + R.drawable.sionsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Sivir', " + R.drawable.sivirsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Skarner', " + R.drawable.skarnersquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Sona', " + R.drawable.sonasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Soraka', " + R.drawable.sorakasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Swain', " + R.drawable.swainsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Syndra', " + R.drawable.syndrasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Talon', " + R.drawable.talonsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Taric', " + R.drawable.taricsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Teemo', " + R.drawable.teemosquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Thresh', " + R.drawable.threshsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Tristana', " + R.drawable.tristanasquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Trundle', " + R.drawable.trundlesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Tryndamere', " + R.drawable.tryndameresquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Twisted Fate', " + R.drawable.twistedfatesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Twitch', " + R.drawable.twitchsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Udyr', " + R.drawable.udyrsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Urgot', " + R.drawable.urgotsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Varus', " + R.drawable.varussquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Vayne', " + R.drawable.vaynesquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Veigar', " + R.drawable.veigarsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Vi', " + R.drawable.visquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Viktor', " + R.drawable.viktorsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Vladimir', " + R.drawable.vladimirsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Volibear', " + R.drawable.volibearsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Warwick', " + R.drawable.warwicksquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Wukong', " + R.drawable.wukongsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Xerath', " + R.drawable.xerathsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Xin Zhao', " + R.drawable.xinzhaosquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Yorick', " + R.drawable.yoricksquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Zac', " + R.drawable.zacsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Zed', " + R.drawable.zedsquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Ziggs', " + R.drawable.ziggssquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Zilean', " + R.drawable.zileansquare + ");";
		db.execSQL(sql);
		sql = "insert into champion_db (name, path) values(" + "'Zyra', " + R.drawable.zyrasquare + ");";
		db.execSQL(sql);
		
		//Will: Insert Attributes into attribute_db
		sql = "insert into attribute_db (name, description) values(" + "'Blind', " + "'Champions that have an ability that blinds enemy champions.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Blink', " + "'Champions that have an ability similar to the summoner spell, Flash.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Dash', " + "'Champions that have a dash ability that allows them to move through and over walls. ''Jumps'' are also included in this category. Note that this is not the same as Blink or the summoner spell Flash.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Execution', " + "'Champions that have an ability that deals more damage based on their target''s missing health.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Global', " + "'Champions that possess an ability that can be used globally.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Haste', " + "'Champions that have an ability that speeds up champions.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Healer', " + "'Champions that have an ability that can heal allies.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Mana Heal', " + "'Champions that possess an ability that restores a specific amount of mana.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Nuke', " + "'Champions that possess an ability that deal significant amounts of damage in a short time. Most nukers are Ability Power-based Champions who rely more on their abilities than their auto-attacks. Their damage output is usually high during the early game, and diminishes as the game progresses.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Pet', " + "'Champions that possess an ability that creates a non-champion ally (sometimes controllable).'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Scout', " + "'Champions that have an ability that grants vision of the map without the use of wards.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Self Heal', " + "'Champions that have an ability to heal themselves, but not other allies.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Shapeshifter', " + "'Champions that have an ability to transform, which grant them a new set of abilities.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Shield', " + "'Champions that possess an ability that creates temporary health, grants damage protection in any way, or grants a damage or spell immunity for a few seconds.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Stance', " + "'Champions that have stances that they can change in and out of instead of the normal abilities that other champions have.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Teleport', " + "'Champions that have an ability similar to the summoner spell, Teleport.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Blocker', " + "'Champions with the ability to create terrain.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Charm', " + "'Champions that have an ability that will charm an enemy. Charmed units will temporarily lose control and wander towards the caster that charmed them. This is not the same as Taunt, but has a similar effect. Currently exclusive to  Ahri.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Fear', " + "'Champions that have an ability that will fear an enemy. Feared units will temporarily lose control and wander around for a short time.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Pull', " + "'Champions with the ability to pull enemy targets toward the caster. Pulled units won''t be able to move, attack or use abilities, similar to Suppress, while being pulled toward the caster. Tenacity does not reduce the time when being pulled.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Knockback', " + "'Champions with the ability to knockback enemy targets. Units knocked back will be sent in a direction much like an uncontrollable dash. Tenacity does not reduce the time when knocked back.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Knockup', " + "'Champions with the ability to knockup enemy targets. Knocked up units will be sent into the air for a short time without control. Tenacity does not reduce the time knocked up.' " + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Silence', " + "'A champion that can silence enemy champions. Champions affected by silence cannot use abilities or summoner spells during its duration.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Stun', " + "'Any champion with at least one ability which inflicts the stun effect on the enemy. It''s important to notice that the stun can work more as a side-effect of the ability in some cases, instead of its main feature.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Taunt', " + "'Champions with the ability to taunt enemy targets. Taunted units will attack the source of the taunt for a limited time without control. They will also follow the source to attack. This is not the same as Charm, but they have similar effects.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Suppress', " + "'All champions that have an ability that is able to suppress. Suppressed units will be unable to move, attack, or use abilities for the duration of the suppression.'" + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Slow', " + "'Any champion with the ability to inflict a slowing effect on the enemy.' " + ");";
		db.execSQL(sql);
		sql = "insert into attribute_db (name, description) values(" + "'Snare', " + "'A champion that can snare enemy champions; champions affected by snares cannot move or use blinks or dashes during its duration.'" + ");";
		db.execSQL(sql);
		
		//Will: Insert values into champion2attributes table
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(1) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(90) + ", " + Integer.toString(1) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(20) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(39) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(40) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(48) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(77) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(98) + ", " + Integer.toString(2) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(3) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(22) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(28) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(29) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(31) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(34) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(43) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(47) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(63) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(67) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(71) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(73) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(79) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(91) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(92) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(94) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(100) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(102) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(109) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(111) + ", " + Integer.toString(3) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(26) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(43) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(73) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(105) + ", " + Integer.toString(4) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(17) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(20) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(25) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(38) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(85) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(5) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(14) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(16) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(17) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(19) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(22) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(25) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(26) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(29) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(37) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(43) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(50) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(56) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(59) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(63) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(64) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(68) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(74) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(75) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(79) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(80) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(83) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(84) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(90) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(96) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(97) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(100) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(105) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(106) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(40) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(41) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(70) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(110) + ", " + Integer.toString(6) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(41) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(59) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(81) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(84) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(85) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(89) + ", " + Integer.toString(7) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(19) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(38) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(39) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(53) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(85) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(86) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(8) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(28) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(81) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(87) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(101) + ", " + Integer.toString(9) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(6) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(50) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(53) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(57) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(77) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(110) + ", " + Integer.toString(10) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(25) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(38) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(44) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(53) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(87) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(90) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(98) + ", " + Integer.toString(11) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(16) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(22) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(25) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(26) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(29) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(31) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(37) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(43) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(57) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(58) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(63) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(64) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(65) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(71) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(75) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(83) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(86) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(94) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(97) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(105) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(106) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(109) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(111) + ", " + Integer.toString(12) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(13) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(62) + ", " + Integer.toString(13) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(13) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(19) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(22) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(26) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(34) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(37) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(41) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(47) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(48) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(50) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(57) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(58) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(63) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(65) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(67) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(68) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(70) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(73) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(74) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(80) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(81) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(83) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(89) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(91) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(97) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(98) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(102) + ", " + Integer.toString(14) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(15) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(84) + ", " + Integer.toString(15) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(97) + ", " + Integer.toString(15) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(67) + ", " + Integer.toString(16) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(16) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(16) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(17) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(2) + ", " + Integer.toString(18) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(29) + ", " + Integer.toString(19) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(63) + ", " + Integer.toString(19) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(77) + ", " + Integer.toString(19) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(105) + ", " + Integer.toString(19) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(14) + ", " + Integer.toString(20) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(20) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(20) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(91) + ", " + Integer.toString(20) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(17) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(29) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(68) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(70) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(79) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(87) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(91) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(92) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(100) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(102) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(109) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(111) + ", " + Integer.toString(21) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(50) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(59) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(73) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(76) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(102) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(109) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(111) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(115) + ", " + Integer.toString(22) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(26) + ", " + Integer.toString(23) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(39) + ", " + Integer.toString(23) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(53) + ", " + Integer.toString(23) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(85) + ", " + Integer.toString(23) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(31) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(34) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(47) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(48) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(58) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(59) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(67) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(68) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(71) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(73) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(76) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(81) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(84) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(87) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(89) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(97) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(100) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(101) + ", " + Integer.toString(24) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(70) + ", " + Integer.toString(25) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(78) + ", " + Integer.toString(25) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(53) + ", " + Integer.toString(26) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(83) + ", " + Integer.toString(26) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(98) + ", " + Integer.toString(26) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(106) + ", " + Integer.toString(26) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(14) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(15) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(16) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(17) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(19) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(25) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(27) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(28) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(31) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(32) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(33) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(35) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(37) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(38) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(39) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(41) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(43) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(44) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(46) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(47) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(48) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(50) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(52) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(56) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(58) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(59) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(64) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(65) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(66) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(67) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(69) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(70) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(74) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(76) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(77) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(80) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(83) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(84) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(86) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(87) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(90) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(91) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(92) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(94) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(95) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(96) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(98) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(105) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(109) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(110) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(111) + ", " + Integer.toString(27) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(37) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(47) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(48) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(58) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(61) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(72) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(75) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);
		sql = "insert into champion2attribute_db (C_id, A_id) values(" + Integer.toString(86) + ", " + Integer.toString(28) + ");"; 
		db.execSQL(sql);	
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		// TODO Auto-generated method stub
		String sql_droptable = "DROP TABLE IF EXISTS" + " champion_db;";
		db.execSQL(sql_droptable);
		sql_droptable = "DROP TABLE IF EXISTS" + " champion2attribute_db;";
		db.execSQL(sql_droptable);
		sql_droptable = "DROP TABLE IF EXISTS" + " attribute_db;";
		db.execSQL(sql_droptable);
		
	}
}
